apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ASIA3MJWW2UGV3PJGQEH
  AWS_SECRET_ACCESS_KEY: 4C6f30F3X0Wm6K6YVZDa5XcDNft2WU+kmN+fEtZH
  AWS_SESSION_TOKEN: FwoGZXIvYXdzECEaDFwXIy8jznRQOHAKhiLGAQpMWW80e5peYFH/EU6Nu/iuozOSyWcFELyDL0+fYojj4cWK2bms4ranmBLfJ9iCHKrjA8bKTmYI85a+r+kuthkUuDRxnGhg6JJmIVYoK/rvtzUxlYY989/WGrDDRFEn70Ap1n42i0SySgBZ0IQMom2XMsDkrgsIBcsO/Df6nmxLGaKhhg2h2QyunfL/xVRB4rrxDv2HtAshdSTP9mMVooh5GBlXLZnAfo2TIh0XwVEEsjaibNY8opnnE6pKPEttkvW0wCPQUCjwj/egBjIthFkx+P4dNxaYwtgHQSNAdX3jDyFPB3vnSq23w3EOMm9/IRwTHnTXqabC8BWq
kind: Secret
metadata:
  creationTimestamp: "2023-03-23T14:13:05Z"
  name: aws-creds
  namespace: default
  resourceVersion: "440731"
  uid: 966a7bd5-cf15-46b6-923e-3e09d70966f2
type: Opaque
