apiVersion: batch/v1
kind: Job
metadata:
  name: market-simulations
spec:
  completions: 9
  parallelism: 9
  template:
    metadata:
      name: market-simulations
    spec:
      containers:
      - name: market-simulations
        image: armandcismaru/deeptrader:deeptrader2.5
      restartPolicy: Never
  backoffLimit: 9
