apiVersion: batch/v1
kind: Job
metadata:
  name: market-simulations
spec:
  completions: 9
  parallelism: 9
  template:
    metadata:
      name: market-simulations
    spec:
      containers:
      - name: market-simulations
        image: armandcismaru/deeptrader:deeptrader-tbse
        # env:
        # - name: AWS_ACCESS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: aws-credentials
        #       key: aws_access_key_id
        # - name: AWS_SECRET_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: aws-credentials
        #       key: aws_secret_access_key
        # - name: AWS_SESSION_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: aws-credentials
        #       key: aws_session_token
      restartPolicy: Never
      # volumes:
      # - name: aws-creds
      #   secret:
      #     secretName: aws-creds
  backoffLimit: 4
