name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install pylint
        pip install numpy
        pip install matplotlib
        pip install keras
        pip install progress
        pip install pandas

    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name "*.py" | xargs)
